---
abstract: 'Utilities for interactive I/O'
author:
  - 'Damian Conway <DCONWAY@cpan.org>'
build_requires:
  Test::More: '1'
configure_requires:
  ExtUtils::MakeMaker: '6.64'
  File::Spec::Functions: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.44, CPAN::Meta::Converter version 2.150010'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: IO-Interactive
no_index:
  directory:
    - t
    - inc
requires:
  perl: '5.008'
resources:
  bugtracker: https://github.com/briandfoy/io-interactive/issues
  homepage: https://github.com/briandfoy/io-interactive
  repository: https://github.com/briandfoy/io-interactive.git
version: '1.023'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
